# Generated by Django 5.1.11 on 2025-01-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the game or activity', max_length=100, unique=True, verbose_name='Game Name')),
                ('description', models.TextField(blank=True, help_text='Description of the game rules or activity', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this game is currently accepting score submissions', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('score_type', models.CharField(choices=[('highest', 'Highest Score Wins'), ('lowest', 'Lowest Score Wins'), ('time', 'Best Time Wins')], default='highest', help_text='How scores should be ranked', max_length=20, verbose_name='Score Type')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['name'],
            },
        ),
    ]
