# Generated by Django 5.1.11 on 2025-01-22 03:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='The score value submitted by the user', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Score')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When the score was submitted', verbose_name='Submitted At')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional game-specific data (e.g., level, time taken)', verbose_name='Metadata')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games.game', verbose_name='Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['user', 'game'], name='scores_scor_user_id_5b8d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['game', '-score'], name='scores_scor_game_id_80b97f_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['game', '-submitted_at'], name='scores_scor_game_id_4f8b6e_idx'),
        ),
    ]
